ALTER TYPE "Product" ADD VALUE IF NOT EXISTS 'AUTO_HOME';

ALTER TYPE "EntityType" ADD VALUE IF NOT EXISTS 'PROPERTY';
ALTER TYPE "EntityType" ADD VALUE IF NOT EXISTS 'CO_APPLICANT';

ALTER TYPE "CollectionActionType" ADD VALUE IF NOT EXISTS 'SELECT_PRODUCT';

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "selectedProduct" "Product";
